drop table if exists human;
create table human (
  id integer generated by default as identity primary key,
  name text,
  birth_year text,
  gender text,
  height integer,
  mass float,
  avatar_url text,
  is_jedi boolean
);

drop table if exists wookie;
create table wookie (
  id integer generated by default as identity primary key,
  name text,
  birth_year text,
  height integer,
  mass float,
  hair_color text
);

drop table if exists droid;
create table droid (
  id integer generated by default as identity primary key,
  name text,
  birth_year text,
  height integer,
  mass float,
  model text
);