drop table if exists human;
create table human (
  id integer generated by default as identity primary key,
  name text,
  birth_year text,
  gender text,
  height integer,
  mass float,
  avatar_url text,
  is_jedi boolean
);