name: CI

on: push

env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}


jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        directory: [
        "solutions/01-how-a-graphql-server-works", 
        "exercices/02-type-system-flexibility", 
        "solutions/02-type-system-flexibility",
        "exercices/04-arguments-and-variables",
        "exercices/07-node",
        "exercices/08-lists-pagination",
      ]
    steps:
      - uses: actions/checkout@v2
      - name: Test ${{ matrix.directory }}
        working-directory: ${{ matrix.directory }}
        run: |
            yarn install
            yarn dump-graphql-schema
            if [[ $(git diff -G. --name-only *.graphql | wc -c) -ne 0 ]]; then echo "The schema is not up to date with the code !" && exit 1; fi
            yarn test --ci
  test-with-db:
    runs-on: ubuntu-latest
    concurrency: 
      group: need_supabase
      cancel-in-progress: false
    strategy:
      fail-fast: false
      matrix:
        directory: [
        "exercices/03-a-complete-graphql-server", 
        "solutions/03-a-complete-graphql-server", 
        "solutions/04-arguments-and-variables",
        "exercices/05-union-and-interface",
        "solutions/05-union-and-interface",
        "exercices/06-mutations",
        "solutions/06-mutations",
        "solutions/07-node",
        "solutions/08-lists-pagination"
      ]
    steps:
      - uses: actions/checkout@v2
      - name: Test ${{ matrix.directory }}
        working-directory: ${{ matrix.directory }}
        run: |
            yarn install
            yarn dump-graphql-schema
            if [[ $(git diff -G. --name-only *.graphql | wc -c) -ne 0 ]]; then echo "The schema is not up to date with the code !" && exit 1; fi
            yarn populate-database
            yarn test --ci