name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test solution 1
        run: |
            cd solutions/01-how-a-graphql-server-works
            yarn install
            yarn test --ci
      - name: Test exercises 2
        run: |
            cd exercices/02-type-system-flexibility
            yarn install
            yarn test --ci
      - name: Test solution 2
        run: |
            cd solutions/02-type-system-flexibility
            yarn install
            yarn test --ci