name: CI

on: push

env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test solution 1
        run: |
            cd solutions/01-how-a-graphql-server-works
            yarn install
            yarn dump-graphql-schema
            yarn test --ci
      - name: Test exercise 2
        run: |
            cd exercices/02-type-system-flexibility
            yarn install
            yarn dump-graphql-schema
            yarn test --ci
      - name: Test solution 2
        run: |
            cd solutions/02-type-system-flexibility
            yarn install
            yarn dump-graphql-schema
            yarn test --ci
      - name: Test exercise 3
        run: |
            cd exercices/03-null-vs-non-null
            yarn install
            yarn dump-graphql-schema
            yarn test --ci
      # TODO add solution 3
      - name: Test exercise 4
        run: |
            cd exercices/04-arguments-and-variables
            yarn install
            yarn dump-graphql-schema
            yarn test --ci
      - name: Test solution 4
        run: |
            cd solutions/04-arguments-and-variables
            yarn install
            yarn dump-graphql-schema
            yarn populate-database
            yarn test --ci
      - name: Test exercise 5
        run: |
            cd exercices/05-union-and-interface
            yarn install
            yarn dump-graphql-schema
            yarn test --ci
      - name: Test solution 5
        run: |
            cd solutions/05-union-and-interface
            yarn install
            yarn dump-graphql-schema
            yarn populate-database
            yarn test --ci
      - name: Test exercise 6
        run: |
            cd exercices/06-mutations
            yarn install
            yarn dump-graphql-schema
            yarn test --ci
      - name: Test solution 6
        run: |
            cd solutions/06-mutations
            yarn install
            yarn dump-graphql-schema
            yarn populate-database
            yarn test --ci
      - name: Test exercise 7
        run: |
            cd exercices/07-node
            yarn install
            yarn dump-graphql-schema
            yarn test --ci
      - name: Test solution 7
        run: |
            cd solutions/07-node
            yarn install
            yarn dump-graphql-schema
            yarn populate-database
            yarn test --ci
      - name: Test exercise 8
        run: |
            cd exercices/08-lists-pagination
            yarn install
            yarn dump-graphql-schema
            yarn test --ci
      - name: Test solution 8
        run: |
            cd solutions/08-lists-pagination
            yarn install
            yarn dump-graphql-schema
            yarn populate-database
            yarn test --ci
      - name: Test exercise 10
        run: |
            cd exercices/10-a-complete-graphql-server
            yarn install
            yarn dump-graphql-schema
            yarn populate-database
            yarn test --ci
      - name: Test solution 10
        run: |
            cd solutions/10-a-complete-graphql-server
            yarn install
            yarn dump-graphql-schema
            yarn populate-database
            yarn test --ci