name: CI

on: push

env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}


jobs:
  test-without-db:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [
        "solutions/01-how-a-graphql-server-works", 
        "exercices/02-type-system-flexibility", 
        "solutions/02-type-system-flexibility"
      ]
    steps:
      - uses: actions/checkout@v2
      - name: Test ${{ matrix.directory }}
        working-directory: ${{ matrix.directory }}
        run: |
            yarn install
            yarn dump-graphql-schema
            if [[ $(git diff -G. --name-only *.graphql | wc -c) -ne 0 ]]; then echo "\n\033[31mThe schema is not up to date with the code\033[0m" && exit 1; fi
            yarn test --ci
      # - name: Test exercise 3
      #   run: |
      #       cd exercices/03-a-complete-graphql-server
      #       yarn install
      #       yarn dump-graphql-schema
      #       yarn populate-database
      #       yarn test --ci
      # - name: Test solution 3
      #   run: |
      #       cd solutions/03-a-complete-graphql-server
      #       yarn install
      #       yarn dump-graphql-schema
      #       yarn populate-database
      #       yarn test --ci
      # - name: Test exercise 4
      #   run: |
      #       cd exercices/04-arguments-and-variables
      #       yarn install
      #       yarn dump-graphql-schema
      #       yarn test --ci
      # - name: Test solution 4
      #   run: |
      #       cd solutions/04-arguments-and-variables
      #       yarn install
      #       yarn dump-graphql-schema
      #       yarn populate-database
      #       yarn test --ci
      # - name: Test exercise 5
      #   run: |
      #       cd exercices/05-union-and-interface
      #       yarn install
      #       yarn dump-graphql-schema
      #       yarn test --ci
      # - name: Test solution 5
      #   run: |
      #       cd solutions/05-union-and-interface
      #       yarn install
      #       yarn dump-graphql-schema
      #       yarn populate-database
      #       yarn test --ci
      # - name: Test exercise 6
      #   run: |
      #       cd exercices/06-mutations
      #       yarn install
      #       yarn dump-graphql-schema
      #       yarn test --ci
      # - name: Test solution 6
      #   run: |
      #       cd solutions/06-mutations
      #       yarn install
      #       yarn dump-graphql-schema
      #       yarn populate-database
      #       yarn test --ci
      # - name: Test exercise 7
      #   run: |
      #       cd exercices/07-node
      #       yarn install
      #       yarn dump-graphql-schema
      #       yarn test --ci
      # - name: Test solution 7
      #   run: |
      #       cd solutions/07-node
      #       yarn install
      #       yarn dump-graphql-schema
      #       yarn populate-database
      #       yarn test --ci
      # - name: Test exercise 8
      #   run: |
      #       cd exercices/08-lists-pagination
      #       yarn install
      #       yarn dump-graphql-schema
      #       yarn test --ci
      # - name: Test solution 8
      #   run: |
      #       cd solutions/08-lists-pagination
      #       yarn install
      #       yarn dump-graphql-schema
      #       yarn populate-database
      #       yarn test --ci